repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff  # Fast Python linter + formatter

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer  # Ensure files end with newline
      - id: trailing-whitespace  # Remove trailing spaces
      - id: check-added-large-files  # Warn if you accidentally commit large files
      - id: check-merge-conflict  # Catch unresolved merge markers
