repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        files: \.py$  # only check Python files
      - id: trailing-whitespace
        files: \.py$  # only clean up Python files
